remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Codewave
description: Software para la Transformación Digital

social-fb: https://www.facebook.com/codewavear
social-x: https://x.com/codewavear
social-ig: https://instagram.com/codewavear
email: vinculacion@unahur.edu.ar

